Feat : Home,commit history,dc modal
delta/codecharacter-web-2023 pull request #10
Opened 2023-01-08 19:35 UTC by shubham-1806

To Do :
- [ ] Add Particle Effect

2023-01-11 18:34 UTC, Ram-20062003 requested changes
## Changes Requested
_Please follow the figma provided_
### Home-Page
- [ ]  Import fonts from `google-fonts` and then use it . `Bai Jamjuree` will not be present by default
- [ ] Change the `Footer` in the front-page. Change the design according to our `new colour` palette
- [ ] Giver darker bg for **Made with :heart: by delta**. Match it with our new design.
- [ ] Look into responsiveness, 
      &emsp;1. `Text overflow` in About page for mobiles.
      &emsp;2. Reduce `font-size` accordingly
      &emsp;3. Have little margin 
- [ ] The `arrow` in the home page should move to second segment when clicked
###  Commit History Page
- [ ]  Use proper fonts here
- [ ] Change the react-code-blocks theme are from `aotmonedark` to `iRBlack`
- [ ] The commit msg area box should be of `uniform size`. Should **not** change for `longer commit messages`.
- [ ] Follow `proper dimensions and colour` as mentioned in figma
- [ ] Vertical timeline component boxes are supposed to be `translucent`
- [ ] Upon clicking `Load Commit`, the committed code should be loaded in main editor
- [ ] Make sure the page is responsive upto `13.1 inches` laptop (1248px).
### Daily Challenge
- [ ] Change the color pallete of the dropdown. Match it with the theme
### General Changes
- [ ] Remove commented and redundant codes
- [ ] Give proper names to the variables
- [ ] Figure out a proper particle background.
- [ ] Remove unwanted files too

Please get these changes done asap. If you have any doubts let me know

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/Home/Glitchtext/Glitchtext.module.css
> +  font-family: 'Bai Jamjuree';
You have download and import this from google-fonts.

2023-01-11 18:34 UTC, Ram-20062003 commented on src/pages/Home/Home.tsx
> +        <img className={styles.arrow} src="/assets/DownArrow.svg"></img>
When the ```arrow``` is clicked it has to move second page segment.

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/CodeMapViewbox/CodeView.tsx
> +// import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
Remove these

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/CodeMapViewbox/CodeView.tsx
> +import { CodeBlock, atomOneDark } from 'react-code-blocks';
`atomOneDark` to `iRBlack` or something darker matching to figma

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/CodeMapViewbox/CodeView.tsx
> +// SyntaxHighlighter.registerLanguage('java', java);
Remove

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/CodeMapViewbox/CodeView.tsx
> +    // </SyntaxHighlighter>
Remove comments

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.module.css
>    font-style: normal;
Font is not properly imported here

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.module.css
> +  font-family: Bai Jamjuree;
here too

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.module.css
> +  font-family: Bai Jamjuree;
Font is not properly imported here

2023-01-11 18:34 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.module.css
> +.modal{
`modal` -> `dcmodal`

2023-01-13 19:31 UTC, Ram-20062003 requested changes
## UI-Changes

### Commit-History Page
![image](https://user-images.githubusercontent.com/83528327/212402370-1ef5dab6-0727-4e71-a60a-ef921057c39a.png)
- [ ] Make **Three** commits to be visible at once.

### Home-Page
- [ ] Replace the image with *previous year map image*
![image](https://user-images.githubusercontent.com/83528327/212402753-e84977a0-feef-47e3-a66f-d52b88ac636e.png)
- [ ] We can have `video-loop` background here too.

### General Changes
- [ ] Play the `video-loop` slower (0.2x) and once the video is done play it in `reverse` direction
- [ ] Remove these un-necessary files. [model.json](https://github.com/delta/codecharacter-web-2023/blob/home%2CcommitHistory%2CDCModal/models.json) and [binary](https://github.com/delta/codecharacter-web-2023/blob/home%2CcommitHistory%2CDCModal/1A3F919CD5B7725108B03C349630A1C82B03_4A84987F2428442A9EC84563BB2BC063)

_(Make sure to do these and the below changes @shubham-1806)_

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
>        <Modal
Make separate these modals as components and import it as a component here

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
>        <Modal
Make a separate component for this Modal too

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
> +          <Button className={styles.dcmodalBtn} onClick={handleCloseAvailable}>
Refer to [react-bootstrap](https://react-bootstrap.github.io/components/buttons/)
```suggestion
<Button variant="outline-danger" onClick={handleCloseAvailable}>
```

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
> +          <Button className={styles.dcmodalBtn} onClick={handleCloseAvailable}>
Refer to [react-bootstrap](https://react-bootstrap.github.io/components/buttons/)
```suggestion
<Button variant="outline-light" onClick={handleCloseAvailable}>
```

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
>            </Button>
- What does this button does here other than closing the modal? Is `Nice` just like `cancel` button.
- `Nice` -> `Ok`
- Refer to [react-bootstrap](https://react-bootstrap.github.io/components/buttons/) and have an `variant` property for it. Make sure it is an `outline` propety

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
> +          <Button className={styles.dcmodalBtn} onClick={handleCloseCompleted}>
```suggestion
<Button variant="outline-info" onClick={handleCloseAvailable}>
```

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
>              View challenges
`View Challenges` -> `View LeaderBoard` . We can redirect him to `daily-challenge leaderboard`.
_(DC-LeaderBoard is not yet ready, you can add the calling latter)_

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/NavBar/NavBar.tsx
>            Commander we hope you are ready for today&apos;s daily chellenge
```suggestion
Commander we hope you are ready for today&apos;s Daily Challenge
```

2023-01-13 19:31 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.tsx
> +  console.log(currentCode);
Remove logs

2023-01-13 19:32 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.tsx
> +      toast.success(` Loaded commit -> ${currentCommitMessage}`);
``` suggestion
      toast.success(` Loaded commit - ${currentCommitMessage}`);
```

2023-01-15 13:35 UTC, Ram-20062003 approved these changes

2023-01-15 13:35 UTC, vigneshd332 approved these changes

2023-01-15 13:36 UTC, merged