Feat: Monaco editor added and css changes in dashboard
delta/codecharacter-web-2023 pull request #12
Opened 2023-01-09 14:06 UTC by bhoopesh369

Added Monaco added and css changes in dashboard
made topbar according to theme (three themes)
added key events 
addded toast messages 
integrated with the backend

2023-01-11 21:55 UTC, Ram-20062003 requested changes
## Changes Requested
![image](https://user-images.githubusercontent.com/83528327/211925465-9829df8d-1ff3-4bc0-a6da-a4af31afcbc6.png)
- In the `top-bar` make the buttons aligned to left, make the elements of the `top-bar` uniform, 
- Add `font-size` and `key-bindings` to `top-bar` itself, because we will be removing the `settings` modal.
(_Take care of the design while adding dropdowns, Make sure it is neat_)
- Make dark as the default theme
- Have another key-binding, `Ctrl+Shift+S` -> `Submits` the code
- `Ctrl+k` commits `empty` message change that

2023-01-11 21:55 UTC, Ram-20062003 commented on .gitmodules
> +	url = https://github.com/delta/codecharacter-web-2023.git
Why are making this repo sub-module to itself :smile: . Remove this

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/Editor/Editor.tsx
> +  const divEl = useRef<HTMLDivElement>(null);
Give proper names.
`div` -> `codeEditor`
(Give meaningful names.)

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/Editor/Editor.tsx
> +  console.log(keyboardHandler);
Remove logs

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/Editor/Editor.tsx
> +      commit();
This function ```commits``` the code directly with `empty` message to backend. 
**Flow**:
It should first ask for a `pop-up`,the user has to enter `commit message` in it and then it has to be committed.

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/EditorSettings/EditorSettings.tsx
> +  const editorThemes = ['vs', 'vs-dark', 'hc-black'];
Change this as follows
```suggestion
  const editorThemes = ['vs-light', 'vs-dark', 'high-contrast-black'];
```

2023-01-11 21:55 UTC, Ram-20062003 commented on src/pages/Dashboard/Dashboard.tsx
> +  const editorThemes = ['vs', 'vs-dark', 'hc-black'];
Change this too
```suggestion
  const editorThemes = ['vs-light', 'vs-dark', 'high-contrast-black'];
```

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/Editor/Editor.tsx
> +    if ((label = 'cpp')) {
Instead of comparing cpp,java,python individually as string. make a `enum` of languages and compare

2023-01-11 21:55 UTC, Ram-20062003 commented on src/components/Editor/Editor.tsx
> +  getWorkerUrl: function (_moduleId: any, label: string) {
Give a valid prop type

2023-01-16 14:11 UTC, bhoopesh369 commented
## Changes Done
-[x] Add `font-size` and `key-bindings` to `top-bar` itself, because we will be removing the `settings` modal.
-[x] Make dark as the default theme
-[x] Have another key-binding, `Ctrl+Shift+S` -> `Submits` the code
-[x] `Ctrl+k` commits `empty` message change that
-[x] 'Add Settings Modal to top bar'
-[x] 'Add Editor shortcuts Modal to TopBar'
-[ ] In the `top-bar` make the buttons aligned to left, make the elements of the `top-bar` uniform,

2023-01-18 22:44 UTC, bhoopesh369 commented
- [x] Commit Modal Added

2023-01-19 16:55 UTC, vigneshd332 requested changes

2023-01-19 16:55 UTC, vigneshd332 commented on .gitmodules
> +[submodule "codecharacter-web-2023"]
bro remove this, the repo cant be a submodule for itself

2023-01-19 16:55 UTC, vigneshd332 commented on src/components/Editor/Editor.tsx
> +// import('monaco-themes/themes/Monokai.json')
remove unnecessary code

2023-01-19 16:55 UTC, vigneshd332 commented on src/pages/Dashboard/Dashboard.tsx
> +              setTrigerCommit={setTrigerCommit}
this is undefined, check if the compoenent works

2023-01-19 16:55 UTC, vigneshd332 commented on src/pages/Dashboard/Dashboard.tsx
>          <SplitPane
fix this type error

2023-01-23 13:12 UTC, vigneshd332 commented
### Changes

- [ ] Remove old Ace Editor dependencies
- [ ] change editor toolbar colour for light mode
- [ ] increase height of editor toolbar

2023-01-26 13:28 UTC, Ram-20062003 requested changes

2023-01-26 13:28 UTC, Ram-20062003 commented on .gitmodules
> +	url = https://github.com/delta/codecharacter-default-codes-2022
add EOF

2023-01-26 13:28 UTC, Ram-20062003 commented on src/components/CommitModal/CommitModal.module.css
> +}
Add EOF

2023-01-26 13:28 UTC, Ram-20062003 commented on src/pages/Dashboard/Dashboard.module.css
> +}
Add EOF here

2023-01-27 12:28 UTC, vigneshd332 approved these changes

2023-01-27 12:28 UTC, vigneshd332 commented on src/components/EditorInfo/EditorInfo.module.css
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
move this import to ```src/main.module.css```

2023-01-27 12:28 UTC, vigneshd332 commented on src/components/EditorInfo/EditorInfo.module.css
> +}
add newline at the end of file

2023-01-27 14:39 UTC, Ram-20062003 approved these changes

2023-01-27 14:43 UTC, merged