feat: Auth Page
delta/codecharacter-web-2023 pull request #13
Opened 2023-01-11 04:46 UTC by Valliammai-SM

2023-01-13 16:52 UTC, vigneshd332 requested changes

2023-01-13 16:52 UTC, vigneshd332 commented on codecharacter-web-2023.iml
> +<?xml version="1.0" encoding="UTF-8"?>
what is this file? Why is this here?

2023-01-13 17:05 UTC, vigneshd332 commented
![image](https://user-images.githubusercontent.com/19623403/212374326-17ea4306-4e92-44ad-96b0-3010f97ab84c.png)

### Changes

- [ ] leave some space between sign in and navbar
- [ ] Reduce font size in the buttons and forgot password according to design
- [ ] center the oauth buttons vertically
- [ ] remove that register in the bottom left corner
- [ ] import the fonts you have used in the <code>src/main.module.css</code> file from google fonts or some other cdn
- [ ] Forgot password on hover make it pointer
- [ ] center that arrow in the login button and make it a little bit bigger
- [ ] change the forgot password modal to match the design

![image](https://user-images.githubusercontent.com/19623403/212376534-6e6e69ac-2019-45cd-8e57-bd8cb537f553.png)

- [ ] Sign Up is in a different position from sign in, please look at the design and see the padding and margin and implement properly
- [ ] leave some of margin between buttons
- [ ] in next button align the arrow center vertically

![image](https://user-images.githubusercontent.com/19623403/212377062-5e1ae1f9-321f-409f-a697-594ea0add75c.png)

- [ ] Height of the country field
- [ ] reduce size of the placeholder font

![image](https://user-images.githubusercontent.com/19623403/212377353-04564c8b-a16c-428d-bc36-fd74267771dd.png)

- [ ] avatar field should have border like design and transparent background

2023-01-15 19:49 UTC, vigneshd332 commented
### Changes

- [ ] Check the password check in Sign Up, its saying error for valid passwords, also give an informative toast about why the password is invalid. You can give specific toasts like ```Password less than 8 characters``` or ```Password should contain atleast one special character, one number...```
- [ ] Update the font in the inputs in sign up
- [ ] clicking next in the signup form reloads the page, fix that
- [ ] fix mobile responsiveness in the signup page and leave some margin between oauth buttons in login page in mobile

2023-01-16 17:46 UTC, Ram-20062003 commented
- [ ] Mobile responsiveness is not yet fixed
- [ ] Give `proper toast messages`( When `password` and `confirm password` does not match  toast `Password and Confirm password doesn't match`) . Change wherever it is necessary
- [ ] Add icons in place-holders

2023-01-18 12:37 UTC, vigneshd332 commented
### Changes

- [ ] Remove the alert component and use the toast function
- [ ] match font size in sign up to login
- [ ] spacing between the oauth buttons and divider is smaller than input fields and divider in sign in page, make them equal
- [ ] college field check is not done in register, complete it
- [ ] remove unused components like alert and progressbar

2023-01-19 16:16 UTC, vigneshd332 commented
![image](https://user-images.githubusercontent.com/19623403/213493632-89bda790-8c04-486c-9add-8f6673064d1b.png)
## Changes

- [x] Add some padding left and right to the highlighted description part in mobile.
- [x] Make avatar field size match the other fields.
- [x] make the login button similar to the one in the signup page (with that arrow mark and no border) for both mobile and web.
- [x] Sign Up has some bugs, look into that.

2023-01-28 07:23 UTC, vigneshd332 requested changes

2023-01-28 07:23 UTC, vigneshd332 commented on src/components/Auth/Auth/Login/IncompleteProfile/incompleteProfile.module.css
> +@import '//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css';
this is not a link la, remove this if youre not using it or move the import to main.module.css with the correct link if its needed

2023-01-28 07:28 UTC, vigneshd332 approved these changes

2023-02-05 13:21 UTC, Ram-20062003 approved these changes

2023-02-05 15:50 UTC, Ram-20062003 approved these changes

2023-02-05 15:50 UTC, merged