Feat : Added Daily Challenges
delta/codecharacter-web-2023 pull request #17
Opened 2023-02-08 13:16 UTC by shubham-1806

2023-02-23 17:33 UTC, vigneshd332 approved these changes

2023-02-24 14:31 UTC, vigneshd332 requested changes

2023-02-24 14:31 UTC, vigneshd332 commented on src/main.module.css
> +
double EOF? 🤨 🤨

2023-02-24 14:33 UTC, Ram-20062003 requested changes

2023-02-24 14:33 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.tsx
> +              <div className={styles.mapLoad}>Loading....</div>
Change `Loading...` -> `Map image not found`

2023-02-24 14:33 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.tsx
> +            mapImg: mapImagesByCommitIds.find(obj => obj.CommitId === id).Image,
```suggestion
mapImagesByCommitIds.find(obj => obj.CommitId === id)
              ?.Image as string
```

2023-02-24 14:33 UTC, Ram-20062003 commented on src/components/CommitHistory/HistoryMain/History.tsx
> +      currentMap.map !== []
```suggestion
      currentMap.map.length !== 0
```

2023-02-24 14:33 UTC, Ram-20062003 commented on src/components/BattleTV/BattleTV.tsx
> +                        ? match.user2.username
```suggestion
                        ? match.user2?.username
```

2023-02-24 14:33 UTC, Ram-20062003 commented on src/components/MapDesigner/MapDesigner.tsx
> +          )}
Put these in useEffect after success api call (getLatestMap)in it.

2023-02-24 14:33 UTC, Ram-20062003 commented on src/pages/Dashboard/Dashboard.tsx
> +    if (dailyChallenge.challType == '') {
Remove this condition check, it is redundant

2023-02-24 14:33 UTC, Ram-20062003 commented on src/store/DailyChallenge/dailyChallenge.ts
> +    challType: '',
```suggestion
    challType: '' as ChallengeType,
```

2023-02-24 16:20 UTC, Ram-20062003 approved these changes

2023-02-24 16:22 UTC, vigneshd332 approved these changes

2023-02-24 16:23 UTC, merged