feat: UI Fixes
delta/codecharacter-web-2023 pull request #22
Opened 2023-02-18 11:54 UTC by Valliammai-SM

2023-02-19 21:51 UTC, Ram-20062003 requested changes
## UI Changes needed
- [x] Please, make `homepage` responsive
- [ ] Fix the `gap` between two segments of the `homepage` (The page containing glitch text and About Page)
- [x] Forget password model is not in sync with other models. Close icon, button are different. Remove that line below `Modal Header`.
- [x] Add labels to the fields in `change-credentials` section as you did in  `user-profile` section
- [ ] There is a random overflow glitch whenever you hover over towers in `map designer page`. Try fixing that too
- [x] The `Start Match` modal in Leader board page is still the old one. Replace it with new theme
- [x] `forum` -> `discord` in home-page
- [ ] Update the contact-info in home-page

2023-02-19 21:59 UTC, Ram-20062003 commented on src/components/DashboardOptions/DashboardOptions.module.css
>  }
Add EOF

2023-03-06 17:15 UTC, Ram-20062003 approved these changes

2023-03-06 19:42 UTC, vigneshd332 approved these changes

2023-03-06 19:42 UTC, merged