Reset tutorials
delta/codecharacter-web-2023 pull request #37
Opened 2023-03-09 16:30 UTC by bhoopesh369

2023-03-09 20:33 UTC, Ram-20062003 requested changes

2023-03-09 20:33 UTC, Ram-20062003 commented on src/components/BattleTV/BattleTV.module.css
> +}
add EOF

2023-03-09 20:33 UTC, Ram-20062003 commented on src/components/DashboardOptions/DashboardOptions.tsx
> +  const User = useAppSelector(user);
why getting a user here? not needed.

2023-03-09 20:33 UTC, Ram-20062003 commented on src/components/DashboardOptions/DashboardOptions.tsx
> +        college: User.college,
Remove redundant updates

2023-03-09 20:33 UTC, Ram-20062003 commented on src/components/DashboardOptions/DashboardOptions.tsx
> +        dispatch(isTourResetChanged(true));
Also make isTourOver false here to open that model
```suggestion
        dispatch(isTourOverChanged(false));
        dispatch(isTourResetChanged(true));
```

2023-03-09 20:33 UTC, Ram-20062003 commented on src/components/Leaderboard/Leaderboard.tsx
> +                                : row.user.username)}
- Always have first 10 char 
```suggestion
                                row.user.username.substring(0, 10)
```
- Do the similar update in `DC-LeaderBoard` and `BattleTv`

2023-03-09 20:33 UTC, Ram-20062003 commented on packages/client/tsconfig.esm.json
> +{
remove pls

2023-03-11 20:21 UTC, Ram-20062003 approved these changes

2023-03-11 20:21 UTC, Ram-20062003 approved these changes

2023-03-12 10:51 UTC, vigneshd332 approved these changes

2023-03-12 14:07 UTC, merged